# Stellar Grooves MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/stellar_grooves

# Stellar Grooves JWT Configuration
stellar.grooves.jwtExpirationMs=86400000

# Server Configuration
server.port=8080
server.address=0.0.0.0

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
